export const metadata = {
  title: 'Privacy Policy — InnerScore',
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <h1 className="font-display text-4xl font-bold text-[#0f172a]">
        Privacy Policy
      </h1>
      <p className="mt-2 text-sm text-[#64748b]">
        Last updated: 12 May 2026
      </p>

      <Section title="1. Data controller">
        <p>
          The controller of your personal data is{' '}
          <strong>FastwaySolutions</strong>, owner of{' '}
          <strong>innerscore.es</strong>.
        </p>
        <p className="mt-3">
          Contact:{' '}
          <a
            href="mailto:privacy@innerscore.es"
            className="text-[#1d4ed8] hover:underline"
          >
            privacy@innerscore.es
          </a>
        </p>
      </Section>

      <Section title="2. Data we collect">
        <List
          items={[
            <>
              <strong>Email address</strong> — provided by you to receive
              your report.
            </>,
            <>
              <strong>Quiz answers</strong> — the 14 numerical responses
              (1–5) you submit during the assessment.
            </>,
            <>
              <strong>Computed result</strong> — overall EQ score,
              dimension scores, and emotional archetype derived from your
              answers.
            </>,
            <>
              <strong>Payment information</strong> — handled directly by
              our payment processor (Stripe). We do not store full card
              details on our servers; we receive only a transaction
              identifier and the email associated with the purchase.
            </>,
            <>
              <strong>Technical data</strong> — minimal log information
              such as IP address and user agent generated by our hosting
              provider for security and operational purposes.
            </>,
          ]}
        />
      </Section>

      <Section title="3. Purposes and legal basis">
        <List
          items={[
            <>
              <strong>To deliver the free EQ assessment and free preview
              of results</strong> — legal basis: performance of a contract /
              implementation of pre-contractual measures at your request
              (Art. 6(1)(b) GDPR).
            </>,
            <>
              <strong>To generate and email the paid 15-page report</strong>{' '}
              — legal basis: performance of a contract (Art. 6(1)(b) GDPR).
            </>,
            <>
              <strong>To process payment</strong> — legal basis:
              performance of a contract and compliance with legal
              obligations (Art. 6(1)(b) and (c) GDPR).
            </>,
            <>
              <strong>To respond to support requests and rights
              requests</strong> — legal basis: legitimate interest in
              providing user support (Art. 6(1)(f) GDPR) and compliance
              with legal obligations under the GDPR.
            </>,
          ]}
        />
      </Section>

      <Section title="4. Recipients (processors)">
        <p>
          We rely on the following processors to operate the service. Each
          acts under a data processing agreement and only processes data on
          our instructions:
        </p>
        <List
          items={[
            <>
              <strong>Stripe</strong> — payment processing.
            </>,
            <>
              <strong>Supabase</strong> — database hosting for purchases.
            </>,
            <>
              <strong>Anthropic</strong> — AI generation of the
              personalized report content based on your quiz answers and
              score.
            </>,
            <>
              <strong>Resend</strong> — email delivery of the PDF report.
            </>,
            <>
              <strong>Vercel</strong> — website and serverless function
              hosting.
            </>,
          ]}
        />
      </Section>

      <Section title="5. International transfers">
        <p>
          Some of our processors are located outside the European Economic
          Area (mainly in the United States). Where this applies, transfers
          are made under appropriate safeguards, such as the European
          Commission&apos;s Standard Contractual Clauses, supplemented by
          additional technical and organizational measures where required.
        </p>
      </Section>

      <Section title="6. Retention">
        <p>
          We retain your email address and purchase record (including quiz
          answers and computed result) for as long as necessary to provide
          the service and to comply with our legal obligations (typically
          accounting and tax records: up to 6 years). After that period the
          data is deleted or anonymized. You can request earlier deletion
          subject to those legal obligations (see Section 8).
        </p>
      </Section>

      <Section title="7. Automated processing">
        <p>
          Your overall EQ score, dimension scores and archetype are
          calculated automatically from your answers. The personalized
          report content is generated by a large language model based on
          those scores and your answers. This processing does not produce
          legal effects on you and is performed at your request as part of
          the service you purchased; it does not constitute automated
          decision-making within the meaning of Art. 22 GDPR.
        </p>
      </Section>

      <Section title="8. Your rights">
        <p>
          Under the GDPR you have the right to: access your personal data;
          have inaccurate data corrected; have your data deleted; restrict
          or object to processing; receive your data in a portable format;
          and withdraw any consent at any time (without affecting the
          lawfulness of processing carried out before the withdrawal).
        </p>
        <p className="mt-3">
          To exercise any of these rights, write to{' '}
          <a
            href="mailto:privacy@innerscore.es"
            className="text-[#1d4ed8] hover:underline"
          >
            privacy@innerscore.es
          </a>
          . We will respond within the periods provided by law.
        </p>
        <p className="mt-3">
          You also have the right to lodge a complaint with the competent
          supervisory authority — in Spain, the{' '}
          <a
            href="https://www.aepd.es"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#1d4ed8] hover:underline"
          >
            Agencia Española de Protección de Datos
          </a>
          .
        </p>
      </Section>

      <Section title="9. Security">
        <p>
          We implement reasonable technical and organizational measures to
          protect personal data against unauthorized access, alteration,
          disclosure or destruction. Connections to the Website are
          encrypted with TLS, and access to backend systems is restricted
          to authorized accounts.
        </p>
      </Section>

      <Section title="10. Changes to this policy">
        <p>
          We may update this Privacy Policy when our processing changes or
          when required by law. We will indicate the date of the last
          revision at the top of this page.
        </p>
      </Section>
    </>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-2xl font-bold text-[#0f172a]">
        {title}
      </h2>
      <div className="mt-3 space-y-3 text-[15px] text-[#0f172a]">
        {children}
      </div>
    </section>
  );
}

function List({ items }: { items: React.ReactNode[] }) {
  return (
    <ul className="mt-2 list-disc space-y-2 pl-6 text-[15px] text-[#0f172a]">
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ul>
  );
}
